name: run-tests

on:
  push:
  schedule:
    - cron: "0 0 * * 0"

jobs:

  php80_to_82:

    name: PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-prefer }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.2, 8.1, "8.0"]
        dependency-prefer: [prefer-stable, prefer-lowest]
        include:
          - php: 8.2
            phpunit: ^9.5.28
          - php: 8.1
            phpunit: ^9.5.28
          - php: 8.0
            phpunit: ^9.5.28

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies (composer)
        run: |
            composer require "phpunit/phpunit:${{ matrix.phpunit }}" --dev --no-interaction --no-update
            composer update --${{ matrix.dependency-prefer }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit



  php70_to_74:

    name: PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-prefer }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [7.4, 7.3, 7.2, 7.1, "7.0"]
        dependency-prefer: [prefer-stable, prefer-lowest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies (composer)
        run: |
          composer require --${{ matrix.dependency-prefer }} --prefer-dist --no-interaction
          composer update --${{ matrix.dependency-prefer }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
